# List of github supported funding platforms

github: burgerbecky
ko_fi: burgerbecky
# open_collective: burgerbecky
patreon: burgerbecky
custom:  ["https://www.paypal.com/donate?token=UvhnElSJnRCUqGR0T4KM0J_c6yWBa0vkH1MNmjYR_1j2d_7gwEfv1-hxwlB6guODVJhwKgAhC9eS2mGy&locale.x=US"]
