# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# burgerlib needs graphviz, and doxygen to build the docs.

# Required
version: 2

# Point to the conf.py file
sphinx:
  configuration: docs/conf.py

# Build Doxygen and pdf
formats:
  - pdf

# Set up all the requirements for python building
python:
  install:
    - requirements: docs/requirements.txt

# Use latest Ubuntu, python, latex and graphviz
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - graphviz
    - texlive-latex-recommended
  # After building the PDF, copy it up
  jobs:
    post_install:
      # Make sure doxygen is the latest version
      - curl --no-progress-meter -O http://logicware.com/downloads/linux/doxygen-1.12.0.tgz
      - tar -xvf doxygen-1.12.0.tgz
      - doxygen -V
      # Burgerlib needs the tool makeheader
      - curl --no-progress-meter -O http://logicware.com/downloads/linux/makeheader.tgz
      - tar -xvf makeheader.tgz
      - makeheader -h
    post_build:
      # Copy the pdf to the final folder
      - cp docs/temp/burgerliblatex/refman.pdf $READTHEDOCS_OUTPUT/pdf/burgerlib.pdf
      - ls -al
      - ls -al docs
      - ls -al $READTHEDOCS_OUTPUT
      - ls -al $READTHEDOCS_OUTPUT/pdf
      - ls -al $READTHEDOCS_OUTPUT/html
      - export

