# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# burgerlib needs graphviz, and doxygen to build the docs.

# Required
version: 2

# Point to the conf.py file
sphinx:
  configuration: docs/conf.py

# Build Doxygen and pdf
formats:
  - pdf

# Set up all the requirements for python building
python:
  install:
    - requirements: docs/requirements.txt

# Use latest Ubuntu, python, latex and graphviz
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - graphviz
    - texlive-latex-recommended
