/***************************************

	Shaders

	Copyright (c) 1995-2016 by Rebecca Ann Heineman <becky@burgerbecky.com>

	It is released under an MIT Open Source license. Please see LICENSE
	for license details. Yes, you can use it in a
	commercial title without paying anything, just give me a credit.
	Please? It's not like I'm asking you for money!
	
***************************************/

#include "brshaders.h"

//
// NOTE!!!
//
// All headers included below are generated by either "stripcomments" for
// OpenGL or the appropriate shader precompiler for the target system
// such as fxc for DirectX or Xbox 360
//
// Do not edit the headers. If editing is needed, edit
// the parent HLSL, GLSL, etc source files.
//

//
// Direct X9 shaders are pre-compiled, and since DirectX demands these
// arrays to be 4 byte aligned, this little weirdness guarantees
// the data is 4 byte aligned
//
// Why? Why must I suffer so?
//

namespace Burger {

#if defined(BURGER_WINDOWS)
#if defined(BURGER_WATCOM)
#define BYTE Word8
#else
#define BYTE __declspec(align(4)) Word8
#endif

// Pixel shaders

#include "pscclr4dx9.h"
#include "pstex2clr4dx9.h"
#include "pstexturedx9.h"
#include "pstexturecolordx9.h"

// Vertex shaders

#include "vs20pos22ddx9.h"
#include "vs20pos2tex2clr42ddx9.h"
#include "vs20sprite2ddx9.h"
#include "vsstaticpositiondx9.h"

#endif

//
// OpenGL source code based shaders
//
// The -1 is to ignore the terminating zero for calls
// that use the literal buffer size instead of using
// "C" strings
//

#if defined(BURGER_OPENGL_SUPPORTED)

// Variable names

const char g_glDiffuseTexture[] = "DiffuseTexture";
const char g_glPosition[] = "Position";
const char g_glTexcoord[] = "Texcoord";
const char g_glColor[] = "Color";
const char g_glViewProjectionMatrix[] = "ViewProjectionMatrix";
const char g_glXYWidthHeight[] = "XYWidthHeight";

// Pixel shaders

#include "pscclr4gl.h"
#include "pstex2clr4gl.h"
#include "pstexturegl.h"
#include "pstexturecolorgl.h"

// Vertex shaders

#include "vs20pos22dgl.h"
#include "vs20pos2tex2clr42dgl.h"
#include "vs20sprite2dgl.h"
#include "vsstaticpositiongl.h"

#endif

//
// Xbox 360 specific shaders
//

#if defined(BURGER_XBOX360)
#define DWORD Word32

// Pixel shaders

#include "pscclr4360.h"
#include "pstex2clr4360.h"
#include "pstexture360.h"
#include "pstexturecolor360.h"

// Vertex shaders

#include "vs20pos22d360.h"
#include "vs20pos2tex2clr42d360.h"
#include "vs20sprite2d360.h"
#include "vsstaticposition360.h"

#endif

//
// Playstation Vita specific shaders
//

#if defined(BURGER_VITA)

// Pixel shaders

#include "pstexturevita.h"
#include "pstexturecolorvita.h"

// Vertex shaders

#include "vs20sprite2dvita.h"
#include "vsstaticpositionvita.h"

#endif
}


