/***************************************

	Global Windows Specific data

	Copyright 1995-2014 by Rebecca Ann Heineman becky@burgerbecky.com

	It is released under an MIT Open Source license. Please see LICENSE
	for license details. Yes, you can use it in a
	commercial title without paying anything, just give me a credit.
	Please? It's not like I'm asking you for money!

***************************************/

#include "brtypes.h"

#if defined(BURGER_WINDOWS)
#define DIRECTINPUT_VERSION 0x800
#define DIRECT3D_VERSION 0x700
#define DIRECTDRAW_VERSION 0x700
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>
#include <dinput.h>
#include <d3d.h>

// Needed for Code Warrior
#ifndef DIDFT_OPTIONAL
#define DIDFT_OPTIONAL 0x80000000
#endif

/***************************************

	These are Windows GUIDs that are used to communicate 
	with DirectX's COM API. They are here so dxguid.lib, dinput.lib
	etc do not need to be linked in. They also retain backward
	compatibility to older, obsolete APIs.

***************************************/

extern "C" const GUID DECLSPEC_SELECTANY IID_IDirect3DTexture = {0x2CDCD9E0,0x25A0,0x11CF,{0xA3,0x1A,0x00,0xAA,0x00,0xB9,0x33,0x56 } };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirect3D = {0x3BBA0080,0x2421,0x11CF,{0xA3,0x1A,0x00,0xAA,0x00,0xB9,0x33,0x56 } };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirect3DHALDevice	= {0x84E63dE0,0x46AA,0x11CF,{0x81,0x6F,0x00,0x00,0xC0,0x20,0x15,0x6E } };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectDraw2 = {0xB3A6F3E0,0x2B43,0x11CF,{0xA2,0xDE,0x00,0xAA,0x00,0xB9,0x33,0x56} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectDrawGammaControl = {0x69C11C3E,0xB46B,0x11D1,{0xAD,0x7A,0x00,0xC0,0x4F,0xC2,0x9B,0x4E} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectDrawSurface3 = {0xDA044E00,0x69B2,0x11D0,{0xA1,0xD5,0x00,0xAA,0x00,0xB8,0xDF,0xBB} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectDraw4 = {0x9c59509a,0x39bd,0x11d1,{0x8c,0x4a,0x00,0xc0,0x4f,0xd9,0x30,0xc5} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectDraw7 = {0x15e65ec0,0x3b9c,0x11d2,{0xb9,0x2f,0x00,0x60,0x97,0x97,0xea,0x5b} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectInput8W = {0xBF798031,0x483A,0x4DA2,{0xAA,0x99,0x5D,0x64,0xED,0x36,0x97,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_SysMouse = {0x6F1D2B60,0xD5A0,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_SysKeyboard = {0x6F1D2B61,0xD5A0,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_Joystick = {0x6F1D2B70,0xD5A0,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_XAxis = {0xA36D02E0,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_YAxis = {0xA36D02E1,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_ZAxis = {0xA36D02E2,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_RxAxis = {0xA36D02F4,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_RyAxis = {0xA36D02F5,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_RzAxis = {0xA36D02E3,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_Slider = {0xA36D02E4,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_Button = {0xA36D02F0,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_Key = {0x55728220,0xD33C,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_POV = {0xA36D02F2,0xC9F3,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectInputEffectDriver = {0x02538130,0x898F,0x11D0,{0x9A,0xD0,0x00,0xA0,0xC9,0xA0,0x6E,0x35} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectInputJoyConfig = {0x1DE12AB1,0xC9F5,0x11CF,{0xBF,0xC7,0x44,0x45,0x53,0x54,0x00,0x00} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectInputPIDDriver = {0xEEC6993A,0xB3FD,0x11D2,{0xA9,0x16,0x00,0xC0,0x4F,0xB9,0x86,0x38} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectInputJoyConfig8 = {0xeb0d7dfa,0x1990,0x4f27,{0xb4,0xd6,0xed,0xf2,0xee,0xc4,0xa4,0x4c} };
extern "C" const GUID DECLSPEC_SELECTANY CLSID_DxDiagProvider = {0xA65B8071,0x3BFE,0x4213,{0x9A,0x5B,0x49,0x1D,0xA4,0x46,0x1C,0xA7} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDxDiagProvider = {0x9C6B4CB0,0x23F8,0x49CC,{0xA3,0xED,0x45,0xA5,0x50,0x00,0xA6,0xD2} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDxDiagContainer = {0x7D0F462F,0x4064,0x4862,{0xBC,0x7F,0x93,0x3E,0x50,0x58,0xC1,0x0F} };
// DirectSound8 GUIDs
extern "C" const GUID DECLSPEC_SELECTANY CLSID_DirectSound = {0x47d4d946,0x62e8,0x11cf,{0x93,0xbc,0x44,0x45,0x53,0x54,0x0,0x0} };
extern "C" const GUID DECLSPEC_SELECTANY CLSID_DirectSound8 = {0x3901cc3f,0x84b5,0x4fa4,{0xba,0x35,0xaa,0x81,0x72,0xb8,0xa0,0x9b} };
extern "C" const GUID DECLSPEC_SELECTANY CLSID_DirectSoundCapture = {0xb0210780,0x89cd,0x11d0,{0xaf,0x8,0x0,0xa0,0xc9,0x25,0xcd,0x16} };
extern "C" const GUID DECLSPEC_SELECTANY CLSID_DirectSoundCapture8 = {0xe4bcac13,0x7f99,0x4908,{0x9a,0x8e,0x74,0xe3,0xbf,0x24,0xb6,0xe1} };
extern "C" const GUID DECLSPEC_SELECTANY CLSID_DirectSoundFullDuplex = {0xfea4300c,0x7959,0x4147,{0xb2,0x6a,0x23,0x77,0xb9,0xe7,0xa9,0x1d} };
extern "C" const GUID DECLSPEC_SELECTANY DSDEVID_DefaultPlayback = {0xdef00000,0x9c6d,0x47ed,{0xaa,0xf1,0x4d,0xda,0x8f,0x2b,0x5c,0x03} };
extern "C" const GUID DECLSPEC_SELECTANY DSDEVID_DefaultCapture = {0xdef00001,0x9c6d,0x47ed,{0xaa,0xf1,0x4d,0xda,0x8f,0x2b,0x5c,0x03} };
extern "C" const GUID DECLSPEC_SELECTANY DSDEVID_DefaultVoicePlayback = {0xdef00002,0x9c6d,0x47ed,{0xaa,0xf1,0x4d,0xda,0x8f,0x2b,0x5c,0x03} };
extern "C" const GUID DECLSPEC_SELECTANY DSDEVID_DefaultVoiceCapture = {0xdef00003,0x9c6d,0x47ed,{0xaa,0xf1,0x4d,0xda,0x8f,0x2b,0x5c,0x03} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IReferenceClock = {0x56a86897,0x0ad4,0x11ce,{0xb0,0x3a,0x00,0x20,0xaf,0x0b,0xa7,0x70} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSound = {0x279AFA83,0x4981,0x11CE,{0xA5,0x21,0x00,0x20,0xAF,0x0B,0xE5,0x60} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSound8 = {0xC50A7E93,0xF395,0x4834,{0x9E,0xF6,0x7F,0xA9,0x9D,0xE5,0x09,0x66} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundBuffer = {0x279AFA85,0x4981,0x11CE,{0xA5,0x21,0x00,0x20,0xAF,0x0B,0xE5,0x60} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundBuffer8 = {0x6825a449,0x7524,0x4d82,{0x92,0x0f,0x50,0xe3,0x6a,0xb3,0xab,0x1e} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_All_Objects = {0xaa114de5,0xc262,0x4169,{0xa1,0xc8,0x23,0xd6,0x98,0xcc,0x73,0xb5} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSound3DListener = {0x279AFA84,0x4981,0x11CE,{0xA5,0x21,0x00,0x20,0xAF,0x0B,0xE5,0x60} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSound3DBuffer = {0x279AFA86,0x4981,0x11CE,{0xA5,0x21,0x00,0x20,0xAF,0x0B,0xE5,0x60} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundCapture = {0xb0210781,0x89cd,0x11d0,{0xaf,0x8,0x0,0xa0,0xc9,0x25,0xcd,0x16} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundCaptureBuffer = {0xb0210782,0x89cd,0x11d0,{0xaf,0x8,0x0,0xa0,0xc9,0x25,0xcd,0x16} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundCaptureBuffer8 = {0x990df4,0xdbb,0x4872,{0x83,0x3e,0x6d,0x30,0x3e,0x80,0xae,0xb6} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundNotify = {0xb0210783,0x89cd,0x11d0,{0xaf,0x8,0x0,0xa0,0xc9,0x25,0xcd,0x16} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IKsPropertySet = {0x31efac30,0x515c,0x11d0,{0xa9,0xaa,0x00,0xaa,0x00,0x61,0xbe,0x93} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXGargle = {0xd616f352,0xd622,0x11ce,{0xaa,0xc5,0x00,0x20,0xaf,0x0b,0x99,0xa3} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXChorus = {0x880842e3,0x145f,0x43e6,{0xa9,0x34,0xa7,0x18,0x06,0xe5,0x05,0x47} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXFlanger = {0x903e9878,0x2c92,0x4072,{0x9b,0x2c,0xea,0x68,0xf5,0x39,0x67,0x83} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXEcho = {0x8bd28edf,0x50db,0x4e92,{0xa2,0xbd,0x44,0x54,0x88,0xd1,0xed,0x42} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXDistortion = {0x8ecf4326,0x455f,0x4d8b,{0xbd,0xa9,0x8d,0x5d,0x3e,0x9e,0x3e,0x0b} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXCompressor = {0x4bbd1154,0x62f6,0x4e2c,{0xa1,0x5c,0xd3,0xb6,0xc4,0x17,0xf7,0xa0} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXParamEq = {0xc03ca9fe,0xfe90,0x4204,{0x80,0x78,0x82,0x33,0x4c,0xd1,0x77,0xda} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXI3DL2Reverb = {0x4b166a6a,0x0d66,0x43f3,{0x80,0xe3,0xee,0x62,0x80,0xde,0xe1,0xa4} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFXWavesReverb = {0x46858c3a,0x0dc6,0x45e3,{0xb7,0x60,0xd4,0xee,0xf1,0x6c,0xb3,0x25} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundCaptureFXAec = {0xad74143d,0x903d,0x4ab7,{0x80,0x66,0x28,0xd3,0x63,0x03,0x6d,0x65} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundCaptureFXNoiseSuppress = {0xed311e41,0xfbae,0x4175,{0x96,0x25,0xcd,0x8,0x54,0xf6,0x93,0xca} };
extern "C" const GUID DECLSPEC_SELECTANY IID_IDirectSoundFullDuplex = {0xedcb4c7a,0xdaab,0x4216,{0xa4,0x2e,0x6c,0x50,0x59,0x6d,0xdc,0x1d} };
extern "C" const GUID DECLSPEC_SELECTANY DS3DALG_NO_VIRTUALIZATION = {0xc241333f,0x1c1b,0x11d2,{0x94,0xf5,0x0,0xc0,0x4f,0xc2,0x8a,0xca} };
extern "C" const GUID DECLSPEC_SELECTANY DS3DALG_HRTF_FULL = {0xc2413340,0x1c1b,0x11d2,{0x94,0xf5,0x0,0xc0,0x4f,0xc2,0x8a,0xca} };
extern "C" const GUID DECLSPEC_SELECTANY DS3DALG_HRTF_LIGHT = {0xc2413342,0x1c1b,0x11d2,{0x94,0xf5,0x0,0xc0,0x4f,0xc2,0x8a,0xca} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_GARGLE = {0xdafd8210,0x5711,0x4b91,{0x9f,0xe3,0xf7,0x5b,0x7a,0xe2,0x79,0xbf} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_CHORUS = {0xefe6629c,0x81f7,0x4281,{0xbd,0x91,0xc9,0xd6,0x04,0xa9,0x5a,0xf6} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_FLANGER = {0xefca3d92,0xdfd8,0x4672,{0xa6,0x03,0x74,0x20,0x89,0x4b,0xad,0x98} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_ECHO = {0xef3e932c,0xd40b,0x4f51,{0x8c,0xcf,0x3f,0x98,0xf1,0xb2,0x9d,0x5d} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_DISTORTION = {0xef114c90,0xcd1d,0x484e,{0x96,0xe5,0x09,0xcf,0xaf,0x91,0x2a,0x21} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_COMPRESSOR = {0xef011f79,0x4000,0x406d,{0x87,0xaf,0xbf,0xfb,0x3f,0xc3,0x9d,0x57} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_PARAMEQ = {0x120ced89,0x3bf4,0x4173,{0xa1,0x32,0x3c,0xb4,0x06,0xcf,0x32,0x31} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_STANDARD_I3DL2REVERB = {0xef985e71,0xd5c7,0x42d4,{0xba,0x4d,0x2d,0x07,0x3e,0x2e,0x96,0xf4} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSFX_WAVES_REVERB = {0x87fc0268,0x9a55,0x4360,{0x95,0xaa,0x00,0x4a,0x1d,0x9d,0xe2,0x6c} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSCFX_CLASS_AEC = {0xBF963D80L,0xC559,0x11D0,{0x8A,0x2B,0x00,0xA0,0xC9,0x25,0x5A,0xC1} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSCFX_MS_AEC = {0xcdebb919,0x379a,0x488a,{0x87,0x65,0xf5,0x3c,0xfd,0x36,0xde,0x40} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSCFX_SYSTEM_AEC = {0x1c22c56d,0x9879,0x4f5b,{0xa3,0x89,0x27,0x99,0x6d,0xdc,0x28,0x10} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSCFX_CLASS_NS = {0xe07f903f,0x62fd,0x4e60,{0x8c,0xdd,0xde,0xa7,0x23,0x66,0x65,0xb5} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSCFX_MS_NS = {0x11c5c73b,0x66e9,0x4ba1,{0xa0,0xba,0xe8,0x14,0xc6,0xee,0xd9,0x2d} };
extern "C" const GUID DECLSPEC_SELECTANY GUID_DSCFX_SYSTEM_NS = {0x5ab0882e,0x7274,0x4516,{0x87,0x7d,0x4e,0xee,0x99,0xba,0x4f,0xd0} };

/***************************************

	Joystick with two x/y/z sticks, two sliders, four POVs and up to 32 buttons

***************************************/

DIOBJECTDATAFORMAT c_rgodfDIJoy[44] = {
	{&GUID_XAxis,FIELD_OFFSET(DIJOYSTATE,lX),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_YAxis,FIELD_OFFSET(DIJOYSTATE,lY),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_ZAxis,FIELD_OFFSET(DIJOYSTATE,lZ),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_RxAxis,FIELD_OFFSET(DIJOYSTATE,lRx),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_RyAxis,FIELD_OFFSET(DIJOYSTATE,lRy),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_RzAxis,FIELD_OFFSET(DIJOYSTATE,lRz),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE,rglSlider[0]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE,rglSlider[1]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE,rgdwPOV[0]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE,rgdwPOV[1]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE,rgdwPOV[2]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE,rgdwPOV[3]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[0]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[1]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[2]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[3]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[4]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[5]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[6]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[7]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[8]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[9]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[10]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[11]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[12]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[13]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[14]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[15]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[16]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[17]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[18]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[19]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[20]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[21]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[22]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[23]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[24]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[25]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[26]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[27]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[28]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[29]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[30]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE,rgbButtons[31]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0}
};

const DIDATAFORMAT c_dfDIJoystick = {
	sizeof(DIDATAFORMAT),sizeof(DIOBJECTDATAFORMAT),		// Buffer sizes
	DIDF_ABSAXIS,				// Absolute axis data
	sizeof(DIJOYSTATE),			// Size of the structure to store into
	sizeof(c_rgodfDIJoy)/sizeof(c_rgodfDIJoy[0]),		// Size of array
	c_rgodfDIJoy
};

/***************************************

	Joystick with two x/y/z sticks, two sliders, four POVs and up to 128 buttons
	and a force, acceleration and velocity x/y/z stick

***************************************/

DIOBJECTDATAFORMAT c_rgodfDIJoy2[164] = {
	{&GUID_XAxis,FIELD_OFFSET(DIJOYSTATE2,lX),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_YAxis,FIELD_OFFSET(DIJOYSTATE2,lY),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_ZAxis,FIELD_OFFSET(DIJOYSTATE2,lZ),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_RxAxis,FIELD_OFFSET(DIJOYSTATE2,lRx),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_RyAxis,FIELD_OFFSET(DIJOYSTATE2,lRy),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_RzAxis,FIELD_OFFSET(DIJOYSTATE2,lRz),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglSlider[0]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglSlider[1]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTPOSITION},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE2,rgdwPOV[0]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE2,rgdwPOV[1]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE2,rgdwPOV[2]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_POV,FIELD_OFFSET(DIJOYSTATE2,rgdwPOV[3]),DIDFT_POV | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[0]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[1]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[2]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[3]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[4]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[5]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[6]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[7]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[8]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[9]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[10]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[11]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[12]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[13]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[14]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[15]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[16]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[17]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[18]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[19]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[20]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[21]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[22]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[23]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[24]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[25]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[26]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[27]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[28]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[29]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[30]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[31]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[32]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[33]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[34]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[35]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[36]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[37]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[38]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[39]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[40]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[41]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[42]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[43]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[44]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[45]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[46]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[47]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[48]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[49]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[50]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[51]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[52]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[53]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[54]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[55]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[56]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[57]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[58]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[59]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[60]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[61]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[62]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[63]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[64]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[65]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[66]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[67]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[68]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[69]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[70]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[71]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[72]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[73]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[74]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[75]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[76]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[77]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[78]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[79]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[80]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[81]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[82]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[83]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[84]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[85]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[86]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[87]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[88]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[89]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[90]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[91]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[92]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[93]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[94]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[95]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[96]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[97]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[98]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[99]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[100]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[101]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[102]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[103]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[104]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[105]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[106]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[107]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[108]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[109]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[110]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[111]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[112]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[113]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[114]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[115]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[116]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[117]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[118]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[119]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[120]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[121]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[122]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[123]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[124]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[125]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[126]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIJOYSTATE2,rgbButtons[127]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_XAxis,FIELD_OFFSET(DIJOYSTATE2,lVX),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_YAxis,FIELD_OFFSET(DIJOYSTATE2,lVY),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_ZAxis,FIELD_OFFSET(DIJOYSTATE2,lVZ),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_RxAxis,FIELD_OFFSET(DIJOYSTATE2,lVRx),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_RyAxis,FIELD_OFFSET(DIJOYSTATE2,lVRy),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_RzAxis,FIELD_OFFSET(DIJOYSTATE2,lVRz),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglVSlider[0]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglVSlider[1]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTVELOCITY},
	{&GUID_XAxis,FIELD_OFFSET(DIJOYSTATE2,lAX),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_YAxis,FIELD_OFFSET(DIJOYSTATE2,lAY),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_ZAxis,FIELD_OFFSET(DIJOYSTATE2,lAZ),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_RxAxis,FIELD_OFFSET(DIJOYSTATE2,lARx),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_RyAxis,FIELD_OFFSET(DIJOYSTATE2,lARy),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_RzAxis,FIELD_OFFSET(DIJOYSTATE2,lARz),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglASlider[0]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglASlider[1]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTACCEL},
	{&GUID_XAxis,FIELD_OFFSET(DIJOYSTATE2,lFX),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE},
	{&GUID_YAxis,FIELD_OFFSET(DIJOYSTATE2,lFY),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE},
	{&GUID_ZAxis,FIELD_OFFSET(DIJOYSTATE2,lFZ),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE},
	{&GUID_RxAxis,FIELD_OFFSET(DIJOYSTATE2,lFRx),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE},
	{&GUID_RyAxis,FIELD_OFFSET(DIJOYSTATE2,lFRy),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE},
	{&GUID_RzAxis,FIELD_OFFSET(DIJOYSTATE2,lFRz),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglFSlider[0]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE},
	{&GUID_Slider,FIELD_OFFSET(DIJOYSTATE2,rglFSlider[1]),DIDFT_AXIS | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,DIDOI_ASPECTFORCE}
};

/***************************************

	Keyboard with 256 optional keys

***************************************/

const DIDATAFORMAT c_dfDIJoystick2 = {
	sizeof(DIDATAFORMAT),sizeof(DIOBJECTDATAFORMAT),		// Buffer sizes
	DIDF_ABSAXIS,				// Absolute axis data
	sizeof(DIJOYSTATE2),		// Size of the structure to store into
	sizeof(c_rgodfDIJoy2)/sizeof(c_rgodfDIJoy2[0]),		// Size of array
	c_rgodfDIJoy2
};

/***************************************

	Keyboard with 256 optional keys

***************************************/

DIOBJECTDATAFORMAT c_rgodfDIKeyboard[256] = {
	{&GUID_Key,0x00,DIDFT_MAKEINSTANCE(0x00) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x01,DIDFT_MAKEINSTANCE(0x01) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x02,DIDFT_MAKEINSTANCE(0x02) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x03,DIDFT_MAKEINSTANCE(0x03) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x04,DIDFT_MAKEINSTANCE(0x04) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x05,DIDFT_MAKEINSTANCE(0x05) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x06,DIDFT_MAKEINSTANCE(0x06) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x07,DIDFT_MAKEINSTANCE(0x07) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x08,DIDFT_MAKEINSTANCE(0x08) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x09,DIDFT_MAKEINSTANCE(0x09) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x0A,DIDFT_MAKEINSTANCE(0x0A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x0B,DIDFT_MAKEINSTANCE(0x0B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x0C,DIDFT_MAKEINSTANCE(0x0C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x0D,DIDFT_MAKEINSTANCE(0x0D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x0E,DIDFT_MAKEINSTANCE(0x0E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x0F,DIDFT_MAKEINSTANCE(0x0F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x10,DIDFT_MAKEINSTANCE(0x10) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x11,DIDFT_MAKEINSTANCE(0x11) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x12,DIDFT_MAKEINSTANCE(0x12) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x13,DIDFT_MAKEINSTANCE(0x13) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x14,DIDFT_MAKEINSTANCE(0x14) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x15,DIDFT_MAKEINSTANCE(0x15) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x16,DIDFT_MAKEINSTANCE(0x16) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x17,DIDFT_MAKEINSTANCE(0x17) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x18,DIDFT_MAKEINSTANCE(0x18) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x19,DIDFT_MAKEINSTANCE(0x19) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x1A,DIDFT_MAKEINSTANCE(0x1A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x1B,DIDFT_MAKEINSTANCE(0x1B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x1C,DIDFT_MAKEINSTANCE(0x1C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x1D,DIDFT_MAKEINSTANCE(0x1D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x1E,DIDFT_MAKEINSTANCE(0x1E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x1F,DIDFT_MAKEINSTANCE(0x1F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x20,DIDFT_MAKEINSTANCE(0x20) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x21,DIDFT_MAKEINSTANCE(0x21) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x22,DIDFT_MAKEINSTANCE(0x22) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x23,DIDFT_MAKEINSTANCE(0x23) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x24,DIDFT_MAKEINSTANCE(0x24) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x25,DIDFT_MAKEINSTANCE(0x25) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x26,DIDFT_MAKEINSTANCE(0x26) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x27,DIDFT_MAKEINSTANCE(0x27) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x28,DIDFT_MAKEINSTANCE(0x28) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x29,DIDFT_MAKEINSTANCE(0x29) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x2A,DIDFT_MAKEINSTANCE(0x2A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x2B,DIDFT_MAKEINSTANCE(0x2B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x2C,DIDFT_MAKEINSTANCE(0x2C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x2D,DIDFT_MAKEINSTANCE(0x2D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x2E,DIDFT_MAKEINSTANCE(0x2E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x2F,DIDFT_MAKEINSTANCE(0x2F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x30,DIDFT_MAKEINSTANCE(0x30) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x31,DIDFT_MAKEINSTANCE(0x31) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x32,DIDFT_MAKEINSTANCE(0x32) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x33,DIDFT_MAKEINSTANCE(0x33) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x34,DIDFT_MAKEINSTANCE(0x34) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x35,DIDFT_MAKEINSTANCE(0x35) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x36,DIDFT_MAKEINSTANCE(0x36) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x37,DIDFT_MAKEINSTANCE(0x37) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x38,DIDFT_MAKEINSTANCE(0x38) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x39,DIDFT_MAKEINSTANCE(0x39) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x3A,DIDFT_MAKEINSTANCE(0x3A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x3B,DIDFT_MAKEINSTANCE(0x3B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x3C,DIDFT_MAKEINSTANCE(0x3C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x3D,DIDFT_MAKEINSTANCE(0x3D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x3E,DIDFT_MAKEINSTANCE(0x3E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x3F,DIDFT_MAKEINSTANCE(0x3F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x40,DIDFT_MAKEINSTANCE(0x40) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x41,DIDFT_MAKEINSTANCE(0x41) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x42,DIDFT_MAKEINSTANCE(0x42) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x43,DIDFT_MAKEINSTANCE(0x43) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x44,DIDFT_MAKEINSTANCE(0x44) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x45,DIDFT_MAKEINSTANCE(0x45) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x46,DIDFT_MAKEINSTANCE(0x46) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x47,DIDFT_MAKEINSTANCE(0x47) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x48,DIDFT_MAKEINSTANCE(0x48) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x49,DIDFT_MAKEINSTANCE(0x49) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x4A,DIDFT_MAKEINSTANCE(0x4A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x4B,DIDFT_MAKEINSTANCE(0x4B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x4C,DIDFT_MAKEINSTANCE(0x4C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x4D,DIDFT_MAKEINSTANCE(0x4D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x4E,DIDFT_MAKEINSTANCE(0x4E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x4F,DIDFT_MAKEINSTANCE(0x4F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x50,DIDFT_MAKEINSTANCE(0x50) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x51,DIDFT_MAKEINSTANCE(0x51) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x52,DIDFT_MAKEINSTANCE(0x52) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x53,DIDFT_MAKEINSTANCE(0x53) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x54,DIDFT_MAKEINSTANCE(0x54) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x55,DIDFT_MAKEINSTANCE(0x55) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x56,DIDFT_MAKEINSTANCE(0x56) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x57,DIDFT_MAKEINSTANCE(0x57) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x58,DIDFT_MAKEINSTANCE(0x58) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x59,DIDFT_MAKEINSTANCE(0x59) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x5A,DIDFT_MAKEINSTANCE(0x5A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x5B,DIDFT_MAKEINSTANCE(0x5B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x5C,DIDFT_MAKEINSTANCE(0x5C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x5D,DIDFT_MAKEINSTANCE(0x5D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x5E,DIDFT_MAKEINSTANCE(0x5E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x5F,DIDFT_MAKEINSTANCE(0x5F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x60,DIDFT_MAKEINSTANCE(0x60) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x61,DIDFT_MAKEINSTANCE(0x61) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x62,DIDFT_MAKEINSTANCE(0x62) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x63,DIDFT_MAKEINSTANCE(0x63) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x64,DIDFT_MAKEINSTANCE(0x64) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x65,DIDFT_MAKEINSTANCE(0x65) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x66,DIDFT_MAKEINSTANCE(0x66) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x67,DIDFT_MAKEINSTANCE(0x67) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x68,DIDFT_MAKEINSTANCE(0x68) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x69,DIDFT_MAKEINSTANCE(0x69) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x6A,DIDFT_MAKEINSTANCE(0x6A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x6B,DIDFT_MAKEINSTANCE(0x6B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x6C,DIDFT_MAKEINSTANCE(0x6C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x6D,DIDFT_MAKEINSTANCE(0x6D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x6E,DIDFT_MAKEINSTANCE(0x6E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x6F,DIDFT_MAKEINSTANCE(0x6F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x70,DIDFT_MAKEINSTANCE(0x70) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x71,DIDFT_MAKEINSTANCE(0x71) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x72,DIDFT_MAKEINSTANCE(0x72) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x73,DIDFT_MAKEINSTANCE(0x73) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x74,DIDFT_MAKEINSTANCE(0x74) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x75,DIDFT_MAKEINSTANCE(0x75) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x76,DIDFT_MAKEINSTANCE(0x76) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x77,DIDFT_MAKEINSTANCE(0x77) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x78,DIDFT_MAKEINSTANCE(0x78) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x79,DIDFT_MAKEINSTANCE(0x79) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x7A,DIDFT_MAKEINSTANCE(0x7A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x7B,DIDFT_MAKEINSTANCE(0x7B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x7C,DIDFT_MAKEINSTANCE(0x7C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x7D,DIDFT_MAKEINSTANCE(0x7D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x7E,DIDFT_MAKEINSTANCE(0x7E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x7F,DIDFT_MAKEINSTANCE(0x7F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x80,DIDFT_MAKEINSTANCE(0x80) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x81,DIDFT_MAKEINSTANCE(0x81) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x82,DIDFT_MAKEINSTANCE(0x82) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x83,DIDFT_MAKEINSTANCE(0x83) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x84,DIDFT_MAKEINSTANCE(0x84) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x85,DIDFT_MAKEINSTANCE(0x85) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x86,DIDFT_MAKEINSTANCE(0x86) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x87,DIDFT_MAKEINSTANCE(0x87) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x88,DIDFT_MAKEINSTANCE(0x88) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x89,DIDFT_MAKEINSTANCE(0x89) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x8A,DIDFT_MAKEINSTANCE(0x8A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x8B,DIDFT_MAKEINSTANCE(0x8B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x8C,DIDFT_MAKEINSTANCE(0x8C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x8D,DIDFT_MAKEINSTANCE(0x8D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x8E,DIDFT_MAKEINSTANCE(0x8E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x8F,DIDFT_MAKEINSTANCE(0x8F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x90,DIDFT_MAKEINSTANCE(0x90) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x91,DIDFT_MAKEINSTANCE(0x91) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x92,DIDFT_MAKEINSTANCE(0x92) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x93,DIDFT_MAKEINSTANCE(0x93) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x94,DIDFT_MAKEINSTANCE(0x94) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x95,DIDFT_MAKEINSTANCE(0x95) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x96,DIDFT_MAKEINSTANCE(0x96) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x97,DIDFT_MAKEINSTANCE(0x97) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x98,DIDFT_MAKEINSTANCE(0x98) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x99,DIDFT_MAKEINSTANCE(0x99) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x9A,DIDFT_MAKEINSTANCE(0x9A) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x9B,DIDFT_MAKEINSTANCE(0x9B) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x9C,DIDFT_MAKEINSTANCE(0x9C) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x9D,DIDFT_MAKEINSTANCE(0x9D) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x9E,DIDFT_MAKEINSTANCE(0x9E) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0x9F,DIDFT_MAKEINSTANCE(0x9F) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA0,DIDFT_MAKEINSTANCE(0xA0) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA1,DIDFT_MAKEINSTANCE(0xA1) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA2,DIDFT_MAKEINSTANCE(0xA2) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA3,DIDFT_MAKEINSTANCE(0xA3) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA4,DIDFT_MAKEINSTANCE(0xA4) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA5,DIDFT_MAKEINSTANCE(0xA5) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA6,DIDFT_MAKEINSTANCE(0xA6) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA7,DIDFT_MAKEINSTANCE(0xA7) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA8,DIDFT_MAKEINSTANCE(0xA8) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xA9,DIDFT_MAKEINSTANCE(0xA9) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xAA,DIDFT_MAKEINSTANCE(0xAA) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xAB,DIDFT_MAKEINSTANCE(0xAB) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xAC,DIDFT_MAKEINSTANCE(0xAC) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xAD,DIDFT_MAKEINSTANCE(0xAD) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xAE,DIDFT_MAKEINSTANCE(0xAE) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xAF,DIDFT_MAKEINSTANCE(0xAF) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB0,DIDFT_MAKEINSTANCE(0xB0) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB1,DIDFT_MAKEINSTANCE(0xB1) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB2,DIDFT_MAKEINSTANCE(0xB2) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB3,DIDFT_MAKEINSTANCE(0xB3) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB4,DIDFT_MAKEINSTANCE(0xB4) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB5,DIDFT_MAKEINSTANCE(0xB5) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB6,DIDFT_MAKEINSTANCE(0xB6) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB7,DIDFT_MAKEINSTANCE(0xB7) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB8,DIDFT_MAKEINSTANCE(0xB8) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xB9,DIDFT_MAKEINSTANCE(0xB9) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xBA,DIDFT_MAKEINSTANCE(0xBA) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xBB,DIDFT_MAKEINSTANCE(0xBB) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xBC,DIDFT_MAKEINSTANCE(0xBC) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xBD,DIDFT_MAKEINSTANCE(0xBD) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xBE,DIDFT_MAKEINSTANCE(0xBE) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xBF,DIDFT_MAKEINSTANCE(0xBF) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC0,DIDFT_MAKEINSTANCE(0xC0) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC1,DIDFT_MAKEINSTANCE(0xC1) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC2,DIDFT_MAKEINSTANCE(0xC2) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC3,DIDFT_MAKEINSTANCE(0xC3) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC4,DIDFT_MAKEINSTANCE(0xC4) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC5,DIDFT_MAKEINSTANCE(0xC5) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC6,DIDFT_MAKEINSTANCE(0xC6) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC7,DIDFT_MAKEINSTANCE(0xC7) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC8,DIDFT_MAKEINSTANCE(0xC8) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xC9,DIDFT_MAKEINSTANCE(0xC9) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xCA,DIDFT_MAKEINSTANCE(0xCA) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xCB,DIDFT_MAKEINSTANCE(0xCB) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xCC,DIDFT_MAKEINSTANCE(0xCC) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xCD,DIDFT_MAKEINSTANCE(0xCD) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xCE,DIDFT_MAKEINSTANCE(0xCE) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xCF,DIDFT_MAKEINSTANCE(0xCF) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD0,DIDFT_MAKEINSTANCE(0xD0) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD1,DIDFT_MAKEINSTANCE(0xD1) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD2,DIDFT_MAKEINSTANCE(0xD2) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD3,DIDFT_MAKEINSTANCE(0xD3) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD4,DIDFT_MAKEINSTANCE(0xD4) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD5,DIDFT_MAKEINSTANCE(0xD5) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD6,DIDFT_MAKEINSTANCE(0xD6) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD7,DIDFT_MAKEINSTANCE(0xD7) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD8,DIDFT_MAKEINSTANCE(0xD8) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xD9,DIDFT_MAKEINSTANCE(0xD9) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xDA,DIDFT_MAKEINSTANCE(0xDA) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xDB,DIDFT_MAKEINSTANCE(0xDB) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xDC,DIDFT_MAKEINSTANCE(0xDC) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xDD,DIDFT_MAKEINSTANCE(0xDD) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xDE,DIDFT_MAKEINSTANCE(0xDE) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xDF,DIDFT_MAKEINSTANCE(0xDF) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE0,DIDFT_MAKEINSTANCE(0xE0) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE1,DIDFT_MAKEINSTANCE(0xE1) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE2,DIDFT_MAKEINSTANCE(0xE2) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE3,DIDFT_MAKEINSTANCE(0xE3) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE4,DIDFT_MAKEINSTANCE(0xE4) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE5,DIDFT_MAKEINSTANCE(0xE5) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE6,DIDFT_MAKEINSTANCE(0xE6) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE7,DIDFT_MAKEINSTANCE(0xE7) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE8,DIDFT_MAKEINSTANCE(0xE8) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xE9,DIDFT_MAKEINSTANCE(0xE9) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xEA,DIDFT_MAKEINSTANCE(0xEA) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xEB,DIDFT_MAKEINSTANCE(0xEB) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xEC,DIDFT_MAKEINSTANCE(0xEC) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xED,DIDFT_MAKEINSTANCE(0xED) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xEE,DIDFT_MAKEINSTANCE(0xEE) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xEF,DIDFT_MAKEINSTANCE(0xEF) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF0,DIDFT_MAKEINSTANCE(0xF0) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF1,DIDFT_MAKEINSTANCE(0xF1) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF2,DIDFT_MAKEINSTANCE(0xF2) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF3,DIDFT_MAKEINSTANCE(0xF3) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF4,DIDFT_MAKEINSTANCE(0xF4) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF5,DIDFT_MAKEINSTANCE(0xF5) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF6,DIDFT_MAKEINSTANCE(0xF6) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF7,DIDFT_MAKEINSTANCE(0xF7) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF8,DIDFT_MAKEINSTANCE(0xF8) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xF9,DIDFT_MAKEINSTANCE(0xF9) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xFA,DIDFT_MAKEINSTANCE(0xFA) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xFB,DIDFT_MAKEINSTANCE(0xFB) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xFC,DIDFT_MAKEINSTANCE(0xFC) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xFD,DIDFT_MAKEINSTANCE(0xFD) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xFE,DIDFT_MAKEINSTANCE(0xFE) | DIDFT_BUTTON | DIDFT_OPTIONAL,0},
	{&GUID_Key,0xFF,DIDFT_MAKEINSTANCE(0xFF) | DIDFT_BUTTON | DIDFT_OPTIONAL,0}
};

const DIDATAFORMAT c_dfDIKeyboard = {
	sizeof(DIDATAFORMAT),sizeof(DIOBJECTDATAFORMAT),		// Buffer sizes
	DIDF_RELAXIS,				// Relative axis data
	256,						// Size of the structure to store into
	sizeof(c_rgodfDIKeyboard)/sizeof(c_rgodfDIKeyboard[0]),		// Size of array
	c_rgodfDIKeyboard
};

/***************************************

	Wheel mouse with 2 buttons (2 optional extra buttons)

***************************************/

DIOBJECTDATAFORMAT c_rgodfDIMouse[7] = {
	{&GUID_XAxis,FIELD_OFFSET(DIMOUSESTATE,lX),DIDFT_AXIS | DIDFT_ANYINSTANCE,0},
	{&GUID_YAxis,FIELD_OFFSET(DIMOUSESTATE,lY),DIDFT_AXIS | DIDFT_ANYINSTANCE,0},
	{&GUID_ZAxis,FIELD_OFFSET(DIMOUSESTATE,lZ),DIDFT_AXIS | DIDFT_ANYINSTANCE,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE,rgbButtons[0]),DIDFT_BUTTON | DIDFT_ANYINSTANCE,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE,rgbButtons[1]),DIDFT_BUTTON | DIDFT_ANYINSTANCE,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE,rgbButtons[2]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE,rgbButtons[3]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0}
};

const DIDATAFORMAT c_dfDIMouse = {
	sizeof(DIDATAFORMAT),sizeof(DIOBJECTDATAFORMAT),		// Buffer sizes
	DIDF_RELAXIS,				// Relative axis data
	sizeof(DIMOUSESTATE),		// Size of the structure to store into
	sizeof(c_rgodfDIMouse)/sizeof(c_rgodfDIMouse[0]),		// Size of array
	c_rgodfDIMouse
};

/***************************************

	Wheel mouse with 2 buttons (6 optional extra buttons)

***************************************/

DIOBJECTDATAFORMAT c_rgodfDIMouse2[11] = {
	{&GUID_XAxis,FIELD_OFFSET(DIMOUSESTATE2,lX),DIDFT_AXIS | DIDFT_ANYINSTANCE,0},
	{&GUID_YAxis,FIELD_OFFSET(DIMOUSESTATE2,lY),DIDFT_AXIS | DIDFT_ANYINSTANCE,0},
	{&GUID_ZAxis,FIELD_OFFSET(DIMOUSESTATE2,lZ),DIDFT_AXIS | DIDFT_ANYINSTANCE,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[0]),DIDFT_BUTTON | DIDFT_ANYINSTANCE,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[1]),DIDFT_BUTTON | DIDFT_ANYINSTANCE,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[2]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[3]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[4]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[5]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[6]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0},
	{&GUID_Button,FIELD_OFFSET(DIMOUSESTATE2,rgbButtons[7]),DIDFT_BUTTON | DIDFT_ANYINSTANCE | DIDFT_OPTIONAL,0}
};

const DIDATAFORMAT c_dfDIMouse2 = {
	sizeof(DIDATAFORMAT),sizeof(DIOBJECTDATAFORMAT),		// Buffer sizes
	DIDF_RELAXIS,				// Relative axis data
	sizeof(DIMOUSESTATE2),		// Size of the structure to store into
	sizeof(c_rgodfDIMouse2)/sizeof(c_rgodfDIMouse2[0]),		// Size of array
	c_rgodfDIMouse2
};

#endif