/***************************************

	This file was generated by a call to
	burger.makeversionheader() from a build
	python script

***************************************/

#ifndef __VERSION_H__
#define __VERSION_H__

#define P4_CHANGELIST 10168
#define P4_CHANGEDATE "2017/01/08"
#define P4_CHANGETIME "18:59:37"
#define P4_CLIENT "burgeroctocore"
#define P4_USER "burgerbecky"

#endif
