/***************************************

	This file was generated by a call to
	burger.makeversionheader() from a build
	python script

***************************************/

#ifndef __P4_VERSION_H__
#define __P4_VERSION_H__

#define P4_CHANGELIST 9696
#define P4_CHANGEDATE "2016/03/14"
#define P4_CHANGETIME "12:35:43"
#define P4_CLIENT "burgeroctocore"
#define P4_USER "burgerbecky"

#endif
