/***************************************

	This file was generated by the
	stripcomments tool

***************************************/

const char g_pstex2clr4gl[] = 
"#ifdef GL_ES\n"
"precision highp float;\n"
"#endif\n"
"PIPED vec2 vPipedTexcoord;\n"
"PIPED vec4 vPipedColor;\n"
"FRAGCOLOR_USED\n"
"uniform sampler2D DiffuseTexture;\n"
"void main(void) {\n"
"gl_FragColor = texture2D(DiffuseTexture,vPipedTexcoord)*vPipedColor;\n"
"}\n";

