/***************************************

	This file was generated by the
	stripcomments tool

***************************************/

const char g_vs20pos2tex2clr42dgl[] = 
"#ifdef GL_ES\n"
"precision highp float;\n"
"#endif\n"
"PIPED vec2 vPipedTexcoord;\n"
"PIPED vec4 vPipedColor;\n"
"uniform vec4 XYWidthHeight;\n"
"const vec4 Adjustments = vec4(2.0,-2.0,-1.0,1.0);\n"
"VERTEX_INPUT vec2 Position;\n"
"VERTEX_INPUT vec2 Texcoord;\n"
"VERTEX_INPUT vec4 Color;\n"
"void main(void) {\n"
"gl_Position = vec4(XYWidthHeight.xy*Adjustments.xy + Adjustments.zw + Position*XYWidthHeight.zw,0,1.0);\n"
"vPipedTexcoord = Texcoord;\n"
"vPipedColor = Color;\n"
"}\n";

